# Generated by Django 2.2 on 2019-07-10 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('IdPlayGame', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Fecha_Hora', models.DateTimeField()),
                ('Result', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game_list',
            fields=[
                ('IdGame', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('NameGame', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(upload_to='imagenes/Profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculo')], max_length=1)),
                ('Partidas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charmi.Game')),
                ('Photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charmi.Photo')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('IdRanking', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=30)),
                ('Cantidad', models.CharField(max_length=30)),
                ('Num_win', models.CharField(max_length=30)),
                ('Num_lose', models.CharField(max_length=30)),
                ('Num_draw', models.CharField(max_length=30)),
                ('Game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo', to='charmi.Game_list')),
                ('Profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rankings', to='charmi.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='IdGame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id_Game', to='charmi.Game_list'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=30)),
                ('Avenue', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='charmi.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accept', models.BooleanField(default=False)),
                ('Follow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Follow_profile', to='charmi.Profile')),
                ('Followers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Followe_profile', to='charmi.Profile')),
            ],
            options={
                'unique_together': {('Followers', 'Follow')},
            },
        ),
    ]
