# Generated by Django 2.2 on 2019-07-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Avenue',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to='charmi.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='Street',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='Cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='Num_draw',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='Num_lose',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='Num_win',
            field=models.IntegerField(),
        ),
    ]
