# Generated by Django 2.2 on 2019-07-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmi', '0002_auto_20190709_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Jugador',
            new_name='Partidas',
        ),
        migrations.AddField(
            model_name='profile',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculo')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
