# Generated by Django 2.2 on 2019-07-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charmi', '0003_auto_20190709_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='IdGame',
            new_name='Game',
        ),
    ]
