# Generated by Django 2.2 on 2019-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmi', '0004_auto_20190709_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='IdRanking',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
