# Generated by Django 2.2 on 2019-07-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmi', '0005_auto_20190709_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='Cantidad',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
